application/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::resource('articles', 'ArticleController');
Route::get('/', 'ApplicationController@index')->name('index');
Route::get('/article-{id}', 'ApplicationController@show')->name('article_show');

application/app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * @property Author $author
 * @property Voice $voices
 * @method static Model|Collection|null find(mixed $key, mixed $default = null)
 */
class Article extends Model
{
    /**
     * To the author of the article
     * @return BelongsTo
     */
    public function author()
    {
        return $this->belongsTo(Author::class, 'authorId');
    }

    /**
     * Get article voices
     * @return HasMany
     */
    public function voices()
    {
        return $this->hasMany(Voice::class, 'articleId');
    }

    /**
     * @return array
     */
    public static function getAllSortByVoicesDefference()
    {
        $articles = Article::paginate(3);
        $articlesWithVoices = [];

        foreach ($articles as $key => $article) {
            $voicesCurrentArticle = $article->voices;
            $articlesWithVoices[$key]['author'] = $article->author->toArray();
            $articlesWithVoices[$key]['article'] = $article->toArray();
            $articlesWithVoices[$key]['difference'] = 0;
            $articlesWithVoices[$key]['likes'] = 0;
            $articlesWithVoices[$key]['dislikes'] = 0;

            foreach ($voicesCurrentArticle as $voice) {
                if ($voice['voice'] === Voice::DISLIKE) {
                    $articlesWithVoices[$key]['difference'] = --$articlesWithVoices[$key]['difference'];
                    $articlesWithVoices[$key]['dislikes'] = ++$articlesWithVoices[$key]['dislikes'];
                } else {
                    $articlesWithVoices[$key]['difference'] = ++$articlesWithVoices[$key]['difference'];
                    $articlesWithVoices[$key]['likes'] = ++$articlesWithVoices[$key]['likes'];
                }
            }
        }

        usort($articlesWithVoices, function($a, $b) {
            if ($a['difference'] == $b['difference']) {
                return 0;
            }
            return $a['difference'] > $b['difference'] ? -1 : 1;
        });

        return [
            $articlesWithVoices,
            $articles
        ];
    }

    /**
     * @param int $id
     * @return array
     */
    public static function getArticleWithVoices($id)
    {
        $collectionArticle = Article::findOrFail((int)$id);
        $voices = $collectionArticle->voices->toArray();

        $article = [];
        $article['article'] = $collectionArticle->toArray();
        $article['author'] = Author::find((int)$article['article']['authorId'])->toArray();
        $article['voices'] = [
            'likes' => 0,
            'dislikes' => 0
        ];

        foreach ($voices as $voice) {
            if ($voice['voice'] === Voice::DISLIKE) {
                $article['voices']['dislikes'] = ++$article['voices']['dislikes'];
            } else {
                $article['voices']['likes'] = ++$article['voices']['likes'];
            }
        }

        return $article;
    }
}

application/app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Article;
use Exception;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        return redirect('/', 302);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $title = 'Create new article';
        $type_query = 'store';

        return view('articles.create', compact('title', 'type_query'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => [
                'required',
                'min:64',
                'max:128'
            ],
            'description' => 'required'
        ]);

        $article = new Article();
        $article->title = $request->title;
        $article->description = $request->description;
        $article->authorId = (int)$request->authorId ?? 1;
        $article->save();

        return redirect()->route('index');
    }

    /**
     * Display the specified resource.
     *
     * @param Request $request
     * @return Response
     */
    public function show(Request $request)
    {
        $id = (int)$request->route('id');

        return redirect()->route('article_show', ['id' => $id]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return Response
     */
    public function edit($id)
    {
        $title = 'Edit article';
        $article = Article::getArticleWithVoices((int)$id);

        return view('articles.edit', compact('title', 'article'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'title' => [
                'required',
                'min:64',
                'max:128'
            ],
            'description' => 'required'
        ]);

        $article = Article::findOrFail((int)$id);
        $article->title = $request->title;
        $article->description = $request->description;
        $article->authorId = (int)$request->authorId ?? 1;
        $article->save();

        return redirect()->route('article_show', ['id' => (int)$id]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return Response
     * @throws Exception
     */
    public function destroy($id)
    {
        $news = Article::find((int)$id);
        $news->delete();

        return redirect()->route('index');
    }
}

application/resources/views/articles/create.blade.php
@extends('base')

@section('main')
<div class="row">
    <div class="col-12">
        @if ($errors->any())
            <div class="alert alert-danger alert-errors-form">
                <ul class="form-errors">
                    @foreach ($errors->all() as $error)
                        <li>{{$error}}</li>
                    @endforeach
                </ul>
            </div>
        @endif
    </div>
    <div class="col-12">
        <form action="{{route('articles.store')}}" method="post">
            @csrf
            <input type="hidden" name="authorId" value="1"/>
            <div class="form-group">
                <label for="title">Title:</label>
                <input id="title" type="text" class="form-control" name="title"/>
            </div>
            <div class="form-group">
                <label for="description">Description:</label>
                <textarea id="description" class="form-control" rows="5" name="description"></textarea>
            </div>
            <hr class="w-100"/>
            <div class="text-right">
                <button type="submit" class="btn btn-primary">Create article</button>
            </div>
        </form>
    </div>
</div>
<hr class="w-100"/>
@endsection

application/resources/views/articles/edit.blade.php
@extends('base')

@section('main')
<div class="row">
    <div class="col-12">
        @if ($errors->any())
            <div class="alert alert-danger alert-errors-form">
                <ul class="form-errors">
                    @foreach ($errors->all() as $error)
                        <li>{{$error}}</li>
                    @endforeach
                </ul>
            </div>
        @endif
    </div>
    <div class="col-12">
        <form action="{{route('articles.update', ['id' => $article['article']['id']])}}" method="post">
            @method('PATCH')
            @csrf
            <input type="hidden" name="authorId" value="{{$article['author']['id']}}"/>
            <div class="form-group">
                <label for="title">Title:</label>
                <input id="title" type="text" class="form-control" name="title" value="{{$article['article']['title']}}"/>
            </div>
            <div class="form-group">
                <label for="description">Description:</label>
                <textarea id="description" class="form-control" rows="5" name="description">{{$article['article']['description']}}</textarea>
            </div>
            <hr class="w-100"/>
            <div class="text-right">
                <button type="submit" class="btn btn-primary">Edit article</button>
            </div>
        </form>
    </div>
</div>
<hr class="w-100"/>
@endsection