application/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::resource('articles', 'ArticleController');
Route::get('/', 'ApplicationController@index')->name('index');
Route::get('/article-{id}', 'ApplicationController@show')->name('article_show');

application/app/Http/Controllers/ApplicationController.php
<?php

namespace App\Http\Controllers;

use App\Article;
use Illuminate\Http\Request;

class ApplicationController extends Controller
{
    public function index()
    {
        $groupArticles = Article::getAllSortByVoicesDefference();
        $articles = $groupArticles[0];
        $articlesPagination = $groupArticles[1];

        return view('application.index', compact('articles', 'articlesPagination'));
    }

    public function show(Request $request)
    {
        $article = Article::getArticleWithVoices((int)$request->route('id'));
        $title = 'Article info';

        return view('application.show', compact('article', 'title'));
    }
}

application/resources/views/application/index.blade.php
@extends('base')

@section('empty-articles')
<div class="alert alert-danger">
    Articles empty...
</div>
@endsection

@section('main')
<div class="articles-list">
    @isset($articles)
        @if(count($articles) > 0)
            @foreach($articles as $article)
            <div class="card card_kidys_theme">
                <div class="card-header">
                    <h3>Title is:&nbsp;<small><a href="{{route('article_show', ['id' => $article['article']['id']])}}">{{$article['article']['title']}}</a></small></h3></div>
                <div class="card-body">
                    {{$article['article']['description']}}
                </div>
                <div class="card-footer">
                    <div class="row justify-content-between">
                        <div class="col-6"><strong>Author is</strong>:&nbsp;{{$article['author']['surname']}} {{$article['author']['name']}}</div>
                        <div class="col-6 text-right"><strong>Likes is</strong>:&nbsp;{{$article['likes']}} | <strong>Dislikes is</strong>:&nbsp;{{$article['dislikes']}}</div>
                    </div>
                </div>
            </div>
            @endforeach
            <hr class="w-100"/>
            <div class="pagination">{{$articlesPagination->links()}}</div>
        @endif
    @endisset
    @empty($articles)
        @yield('empty-articles')
    @endempty
</div>
<hr class="w-100"/>
@endsection

application/resources/views/application/show.blade.php
@extends('base')

@section('main')
<div class="row">
    <div class="col-12">
        <div class="article-item">
            <div class="article-nav row justify-content-end">
                <div class="col-auto">
                    <div class="row no-gutters">
                        <a class="btn btn-primary" href="{{route('articles.edit', ['id' => $article['article']['id']])}}">Edit</a>
                        &nbsp;
                        <form action="{{route('articles.destroy', ['id' => $article['article']['id']])}}" method="post" class="col-auto">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                    </div>
                </div>
            </div>
            <hr class="w-100"/>
            <div class="card card_kidys_theme">
                <div class="card-header">
                    <h3>Title is:&nbsp;<small>{{$article['article']['title']}}</small></h3>
                </div>
                <div class="card-body">
                    {{$article['article']['description']}}
                </div>
                <div class="card-footer">
                    <div class="row justify-content-between">
                        <div class="col-6"><strong>Author is</strong>:&nbsp;{{$article['author']['surname']}} {{$article['author']['name']}}</div>
                        <div class="col-6 text-right"><strong>Likes is</strong>:&nbsp;{{$article['voices']['likes']}} | <strong>Dislikes is</strong>:&nbsp;{{$article['voices']['dislikes']}}</div>
                    </div>
                </div>
            </div>
        </div>
        <hr class="w-100"/>
    </div>
</div>
@endsection